# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferencePaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('conference_name', models.CharField(max_length=30)),
                ('pdf_file_c', models.FileField(upload_to='paper/conference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JournalPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('journal_name', models.CharField(max_length=30)),
                ('pdf_file_j', models.FileField(upload_to='paper/journal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
