# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0003_auto_20160428_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencepaper',
            name='pdf_filename_c',
            field=models.CharField(blank=True, default=None, editable=False, max_length=30),
        ),
    ]
