# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0004_auto_20160428_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalpaper',
            name='pdf_filename_j',
            field=models.CharField(blank=True, default=None, editable=False, max_length=30),
        ),
    ]
