# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0005_journalpaper_pdf_filename_j'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencepaper',
            name='conference_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='conferencepaper',
            name='pdf_filename_c',
            field=models.CharField(blank=True, default=None, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='conferencepaper',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='journalpaper',
            name='journal_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='journalpaper',
            name='pdf_filename_j',
            field=models.CharField(blank=True, default=None, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='journalpaper',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
