# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import memory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('main_photo', models.ImageField(upload_to=memory.models.photo_directory_path)),
                ('main_thumbnail', models.ImageField(editable=False, upload_to=memory.models.thumbnail_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_file', models.ImageField(upload_to=memory.models.photo_directory_path)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory.Memory')),
            ],
        ),
    ]
